---
platform: linux

inputs:
  - name: source
  - name: version

run:
  path: /bin/bash
  args:
    - -exc
    - |
      ls version
      export VERSION=$(cat version/marman)
      pushd source
      make build-all
      popd

outputs:
  - name: build
    path: source/build