---
platform: linux

inputs:
  - name: source
  - name: version

run:
  path: /bin/bash
  args:
    - -exc
    - |
      cat version/version
      cat version/number
      export VERSION=$(cat version/version)
      pushd source
      make build-all
      popd

outputs:
  - name: build
    path: source/build